export const KafkaTopics = {
  TripRequested: 'trip.requested',
  TripAccepted: 'trip.accepted',
  TripCancelled: 'trip.cancelled',
  TripStarted: 'trip.started',
  TripCompleted: 'trip.completed',
  TripCreated: 'trip.created',
  TripSearchStarted: 'trip.search.started',
  TripSearchExpanded: 'trip.search.expanded',
  TripSearchFailed: 'trip.search.failed',
  TripStatusChanged: 'trip.status.changed',
  TripRiderNotified: 'trip.rider.notified',
  TripRiderAccepted: 'trip.rider.accepted',
  TripRiderRejected: 'trip.rider.rejected',
  TripRiderAssigned: 'trip.rider.assigned',
  RiderLocationUpdated: 'rider.location.updated',
  RiderStatusChanged: 'rider.status.changed',
  LocationUpdated: 'location.updated',
  WalletTransactionCreated: 'wallet.transaction.created',
  NotificationSendRequested: 'notification.send.requested',
  AuthUserRegistered: 'auth.user_registered',
  AuthUserLoggedIn: 'auth.user_logged_in',
  AuthOtpRequested: 'auth.otp_requested',
  AuthPasswordChanged: 'auth.password_changed',
  UserProfileUpdated: 'user.profile.updated',
  UserAddressCreated: 'user.address.created',
  UserAddressUpdated: 'user.address.updated',
  UserAddressDeleted: 'user.address.deleted',
  UserFavoriteCreated: 'user.favorite.created',
  UserFavoriteUpdated: 'user.favorite.updated',
  UserFavoriteDeleted: 'user.favorite.deleted',
  UserSettingsUpdated: 'user.settings.updated',
} as const;

export type KafkaTopic = (typeof KafkaTopics)[keyof typeof KafkaTopics];
